name: Build at home version (Windows)

on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
      - 'public/**'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
    steps:
    # Set up js package
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set package version and name
      uses: brown-ccv/gh-actions/get-package-info@master
      id: package_info

    # install, test, build package
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build:win:home:video
      env:
        REACT_APP_AT_HOME: true
        REACT_APP_VIDEO: true

    # Build electron app package installers
    - name: package electron - windows
      run: npm run package:windows

    # Upload installers to github action
    - name: upload win-installer-home
      uses: actions/upload-artifact@master
      with:
        name: win-installer-home
        path: dist/installers/${{ steps.package_info.outputs.package_name }}-${{ steps.package_info.outputs.package_version }}-setup.exe
